version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = [
    "nodejs",
    "jest",
    "mongo",
    "browser"
]
dependency_file_paths = [
    "client/package.json",
    "server/package.json",
    "client/package.lock",
    "server/package.lock"
]
plugins = ["react"]
style_guide = "airbnb"
