version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = [
    "nodejs",
    "jest",
    "mongo",
    "browser"
]
module_system = "es-modules"
style_guide = "airbnb"
